blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Maximka1993271/SoundForge-Equalizer/discussions
    about: Ask questions and discuss ideas here.
  - name: 📖 Wiki
    url: https://github.com/Maximka1993271/SoundForge-Equalizer/wiki
    about: Check the documentation and guides.
